server:
  port: 8001
spring:
  application:
    name: cloud-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-while-idle: false #关闭空闲检测
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001 #显示实例名称
    prefer-ip-address: true  #显示访问ip地址
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jg.springcloud.entities

logging:
  level:
    com.jg.springcloud.dao: debug

