server:
  port: 7001

#eureka\u5730\u5740
eureka.name: localhost
eureka.remote.port1: 7002
eureka:
  instance:
    hostname: eureka7001.com  #eurekaeureka服务实例名称
  client:
    register-with-eureka: false    #是否将自己也注册进注册中心
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.name}:${eureka.remote.port1}
      defaultZone: http://eureka7002.com:7002/eureka    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
  server:
    enable-self-preservation: false #自我保护机制关闭 默认是开启的
    eviction-interval-timer-in-ms: 2000 #心跳周期设置




